steps:
  - id: "Rodando Teste da aplicação"
    name: "gcr.io/cloud-builders/go"
    args: ["test", "./src/sqrt"]
    env: ["GOPATH=."]

  - id: "Compilando Golang"
    name: "gcr.io/cloud-builders/go"
    args: ["build", "-o", "./src/sqrt", "./src/sqrt"]
    env: ["GOPATH=."]

  - id: "Montando Imagem Docker"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/desafio-go-hpa:latest", "."]

images:
  - "gcr.io/$PROJECT_ID/desafio-go-hpa:latest"
