apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  selector:
    matchLabels:
      run: go-hpa
  replicas: 1
  template:
    metadata:
      labels:
        run: go-hpa
    spec:
      containers:
        - name: pgo-hpa
          image: jhortale/go-hpa
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 50m
